name: MCW
version: 1.0-SNAPSHOT
main: com.cragon.mcw.MCW
api-version: 1.13
authors: [CraftyDragon678]
description: Skill
website: https://github.com/CraftyDragon678
commands:
  mcw:
    description: mcw
